In [4]:
#!pip install torch
torch.__version__

'1.8.1'

In [2]:
import torch

# Tensors

In [6]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [8]:
# 1-d
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

tensor should be of same datatype only. pytorch will typecast if necessary

In [14]:
# matrix - 2d
t3 = torch.tensor([[5.,6], [7,8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [16]:
# 3d
t4 = torch.tensor([[[11, 12, 13], [14, 15, 16]], [[15, 16, 17], [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

How is a tensor different from a list of list of lists ??

Tensor should have a regular shape. Each row should have a certain number of columns. Cannot be different

In [18]:
t4 = torch.tensor([[[11, 12, 13], [14, 15, 16, 20]], [[15, 16, 17], [17, 18, 19.]]])
t4

ValueError: expected sequence of length 3 at dim 2 (got 4)

#### shapes

In [19]:
t1.shape, t2.shape, t3.shape, t4.shape

(torch.Size([]), torch.Size([4]), torch.Size([3, 2]), torch.Size([2, 2, 3]))

# Tensor Operations and Gradients

In [20]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [21]:
y = w * x + b

pytorch can automatically compute of the derivate of y w.r.t to the tensors that have ```requires_grad=True``` 

To compute derivates we call ```backward``` function

In [23]:
y.backward()

In [26]:
# Display gradients
print('dx/dy : ', x.grad)
print('dw/dy : ', w.grad)
print('db/dy : ', b.grad)

dx/dy :  None
dw/dy :  tensor(3.)
db/dy :  tensor(1.)


# Interoperability with numpy

In [41]:
import numpy as np
np_array = np.array([[1.,2], [2,3]])
np_array

array([[1., 2.],
       [2., 3.]])

In [42]:
y = torch.from_numpy(np_array)
y

tensor([[1., 2.],
        [2., 3.]], dtype=torch.float64)

In [43]:
## can also do torch.tensor but this takes a copy and consumes additional space
y = torch.tensor(np_array)
y

tensor([[1., 2.],
        [2., 3.]], dtype=torch.float64)

In [44]:
np_array.dtype, y.dtype

(dtype('float64'), torch.float64)

convert ```tensor``` to ```numpy```

In [46]:
y.numpy()

array([[1., 2.],
       [2., 3.]])

one of the purpose of torch tensors is for gpu support